<?php

return [
    'order_prefix' => env('SHOP_ORDER_PREFIX', 'ORD'),
    'order_start' => (int) env('SHOP_ORDER_START', 10001),
    'currency' => env('SHOP_CURRENCY', 'INR'),
    'currency_symbol' => env('SHOP_CURRENCY_SYMBOL', '₹'),
    'admin_email' => env('SHOP_ADMIN_EMAIL', 'admin@blackrossy.com'),
    'cart_cookie' => 'blackrossy_cart',
    'cart_cookie_days' => 30,
    'duplicate_order_minutes' => 15,
    'max_orders_per_ip_day' => 8,
    'max_orders_per_mobile_day' => 5,
    'otp_ttl_minutes' => 10,
    'low_stock_threshold' => 5,
    'related_limit' => 8,
    'listing_per_page' => 24,
    'search_suggestions' => 8,
    'image' => [
        'max_kb' => 4096,
        'mimes' => ['jpg', 'jpeg', 'png', 'webp'],
        'thumb' => 400,
        'medium' => 800,
        'large' => 1400,
        'quality' => 82,
    ],
    'ad_positions' => [
        'home_top' => 'Homepage — after featured products',
        'home_middle' => 'Homepage — after trending products',
        'home_bottom' => 'Homepage — before blog',
        'category_top' => 'Category — top',
        'category_middle' => 'Category — middle',
        'category_bottom' => 'Category — bottom',
        'listing_middle' => 'Listing — after product grid row',
        'listing_bottom' => 'Listing — bottom',
        'product_middle' => 'Product — after buy box',
        'product_bottom' => 'Product — after description',
        'search_middle' => 'Search results — middle',
        'blog_top' => 'Blog — top',
        'blog_middle' => 'Blog — middle',
        'blog_bottom' => 'Blog — bottom',
    ],
];
